Description: This is a silly Discord bot.

Parameters:
  PaywallBotToken:
    Type: String
    Default: Get it from Discord if you don't have it. Don't just make it up.
    Description: Enter the token for your paywall bot.

Resources:

  PaywallBotTokenParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: PaywallBot Token
      Name: paywallbot-token
      Type: String
      Value: !Ref PaywallBotToken

  PaywallTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: PaywallBotPaywall
      AttributeDefinitions: 
        - AttributeName: guild_id
          AttributeType: N
        - AttributeName: paywall_url
          AttributeType: S          
      KeySchema: 
        - AttributeName: guild_id
          KeyType: HASH   
        - AttributeName: paywall_url
          KeyType: RANGE        
      Tags:
          - Key: Vendor
            Value: PaywallBot
          - Key: Name
            Value: PaywallBotPaywall

  EmojiTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: PaywallBotEmoji 
      AttributeDefinitions: 
        - AttributeName: guild_id
          AttributeType: N
        - AttributeName: emoji_id
          AttributeType: N          
      KeySchema: 
        - AttributeName: guild_id
          KeyType: HASH   
        - AttributeName: emoji_id
          KeyType: RANGE         
      Tags:
          - Key: Vendor
            Value: PaywallBot
          - Key: Name
            Value: PaywallBotEmoji         

  ReplyTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: PaywallBotReply 
      AttributeDefinitions: 
        - AttributeName: guild_id
          AttributeType: N
        - AttributeName: reply
          AttributeType: S          
      KeySchema: 
        - AttributeName: guild_id
          KeyType: HASH   
        - AttributeName: reply
          KeyType: RANGE         
      Tags:
          - Key: Vendor
            Value: PaywallBot
          - Key: Name
            Value: PaywallBotReply  

  BlockedUserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: PaywallBotBlockedUser
      AttributeDefinitions: 
        - AttributeName: guild_id
          AttributeType: N
        - AttributeName: user_id
          AttributeType: N        
      KeySchema: 
        - AttributeName: guild_id
          KeyType: HASH   
        - AttributeName: user_id
          KeyType: RANGE         
      Tags:
          - Key: Vendor
            Value: PaywallBot
          - Key: Name
            Value: PaywallBotBlockedUser                              

  PaywallBotTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:  
              - Effect: Allow
                Action: "dynamodb:*"
                #arnrewrite
                Resource: 
                  - !GetAtt PaywallTable.Arn
                  - !GetAtt EmojiTable.Arn
                  - !GetAtt ReplyTable.Arn
                  - !GetAtt BlockedUserTable.Arn
              - Effect: Allow
                Action: "ssm:*"
                #arnrewrite
                Resource: 
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/paywallbot-token                 
      Tags:
          - Key: Vendor
            Value: PaywallBot
          - Key: Name
            Value: PaywallBotTaskRole            